general {
    grace = 0
    hide_cursor = false
    no_fade = false
}

# wallpaper o fondo
background {
    monitor =
    path = ~/.config/sway/wallpaper/dm.jpg
    color = rgba(161616ff)
}

# Input para password
input-field {
    size = 250, 50
    outline_thickness = 2
    rounding = 2                       # cuadrado perfecto
    inner_color = rgba(060606ff)        # fondo gris oscuro
    outer_color = rgba(060606ff)        # borde gris
    font_color = rgba(ffffffff)         # texto claro
    font_family = JetBrains Mono
    placeholder_text =  PASS
    hide_input = false
    fade_on_empty = false
    dots_size = 0.25
    dots_spacing = 0.5
    dots_center = true
    check_color = rgba(060606ff)
    fail_color = rgba(060606ff)
    fail_text = Error

    # ← Aquí los cambios clave para centrarlo
    halign = center                     # alineación horizontal: centro
    valign = center                     # alineación vertical: centro
    position = 0, -507                  # 0 en X (centro horizontal), -120 en Y (un poco arriba del centro vertical)
}

# Horas
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(f4f4f4ff)
    font_size = 50
    font_family = JetBrains Mono Bold 
    position = -825, 475
    valign = center
}

# Dia 
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A %d")"
    color = rgba(f4f4f4aa)
    font_size = 12
    font_family = JetBrains Mono bold
    position = -825, 425
    valign = center
    halign = center
}

# Imagen en cuadro (no wallpaper)
image {
    monitor =
    path = ~/.config/sway/wallpaper/dm.jpg
    size = 100
    border_size = 0
    border_color = rgba(be95ffff)
    rounding = 2
    asp_correction = true
    halign = right
    valign = center
    position = -20,-470
}

# Usuario actual
label {
monitor =
text = @$USER
color = rgba(f4f4f4ff)
background = rgba(232323ff)
font_size = 13
font_family = JetBrains Mono Bold
position = -70, -470
valign = center
halign = right
}



# Recctangulo
shape {
    monitor =                     # vacío = todos los monitores
    size = 1915, 60               # ancho x alto en píxeles (ajusta a tu gusto)
    color = rgba(060606ff)        # relleno gris oscuro semitransparente (tu --oxo-bg-secondary con algo de alpha)
    rounding = 0                  # 0 = rectángulo perfecto (sin redondeo). Usa >0 para esquinas redondeadas si cambias de idea
    border_size = 3               # grosor del borde (0 = sin borde)
    border_color = rgba(060606ff) # color del borde (tu --oxo-border)
    rotate = 0                    # rotación en grados (0 = horizontal)
    xray = false                  # false = rectángulo normal. true = "agujero" en el fondo (ver abajo)
    position = 0, 0               # offset desde el centro (0,0 = centrado perfecto)
    halign = center               # alineación horizontal: center / left / right
    valign = bottom               # alineación vertical: center / top / bottom
    zindex = 0                    # capa (0 = detrás de todo, sube si quieres encima)
}

# Compositor
label {
    monitor =
    text = cmd[update:0] echo "$XDG_CURRENT_DESKTOP" | tr '[:lower:]' '[:upper:]'
    color = rgba(f4f4f4ff)
    background = rgba(060606ff)
    font_size = 13
    font_family = JetBrains Mono Bold
    position = -825, -475
    valign = center
    halign = center
}
