return {
  {
    "glepnir/dashboard-nvim",
    event = "VimEnter",
    config = function()
      require("dashboard").setup({
        theme = "doom",
        config = {
          header = {
            -- "",
            -- "",
            -- "",
            -- -- "",
            -- "",
            -- "",
            -- "",
            -- "",
            -- "",
            -- "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "██████   █████  ███    ███  █████  ██    ██  █████ ",
            "██   ██ ██   ██ ████  ████ ██   ██ ██    ██ ██   ██",
            "██   ██ ███████ ██ ████ ██ ███████   ████   ███████",
            "██   ██ ██   ██ ██  ██  ██ ██   ██    ██    ██   ██",
            "██████  ██   ██ ██      ██ ██   ██    ██    ██   ██",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          },
          center = {
            { icon = " ", desc = "Find File", key = "f", action = "lua Snacks.picker.files()" },
            { icon = " ", desc = "Open Project", key = "p", action = "lua Snacks.picker.files({ cwd = vim.fn.expand('~') })" },
            { icon = "󰈈 ", desc = "Live Grep", key = "g", action = "lua Snacks.picker.grep()" },
            { icon = "󰂺 ", desc = "Find TODO", key = "t", action = "lua Snacks.picker.grep({ search = 'TODO', prompt = 'Find TODO: ' })" },
            { icon = " ", desc = "Find WARN", key = "w", action = "lua Snacks.picker.grep({ search = 'WARN', prompt = 'Find WARN: ' })" },
            { icon = "󱓧 ", desc = "Find NOTE", key = "n", action = "lua Snacks.picker.grep({ search = 'NOTE', prompt = 'Find NOTE: ' })" },
            { icon = " ", desc = "Config", key = "c", action = "lua Snacks.picker.files({ cwd = 'C:~/.config/nvim/', prompt = 'Config Files' })" },
            { icon = " ", desc = "Quit", key = "q", action = "quit" },
            -- Adicionales que podrías agregar:
            { icon = " ", desc = "Buffers", key = "b", action = "lua Snacks.picker.buffers()" },
            { icon = "󰊢 ", desc = "Git Files", key = "G", action = "lua Snacks.picker.git_files()" },
            { icon = "󰞋 ", desc = "Help", key = "h", action = "lua Snacks.picker.help()" },
            { icon = "󱁤 ", desc = "Commands", key = "C", action = "lua Snacks.picker.commands()" },
          },
          footer = {
            "",
            "",
            " NvChad Configs by JACP / Nen None / Kin Damaya.",
            "",
            "",
          },
        },
      })
    end,
  },
} 
